import ForgotPassword from "modules/ForgotPassword";
import GenerateRecipe from "modules/GenerateRecipe";
import ListDetailRecipes from "modules/ListDetailRecipes";
import EditSport from "modules/EditPerfil/EditSport";
import EditWeight from "modules/EditPerfil/EditWeight";
import EditTrainingLevel from "modules/EditPerfil/EditTrainingLevel";
import EditSex from "modules/EditPerfil/EditSex";

const Routes = {
  Walkthoughs: "Walkthoughs",
  SignUp: "SignUp",
  StepOne: "StepOne",
  StepTwo: "StepTwo",
  StepThree: "StepThree",
  StepFour: "StepFour",
  StepFive: "StepFive",
  StepSix: "StepSix",
  Login: "Login",
  ForgotPassword: "ForgotPassword",
  MainTab: "MainTab",
  Diary: "Diary",
  Exercires: "Exercires",
  Workouts: "Workouts",
  More: "More",
  SearchExercires: "SearchExercires",
  AddExercire: "AddExercire",
  AutoTracking: "AutoTracking",
  MuscleGroup: "MuscleGroup",
  ChestExercises: "ChestExercises",
  ExercireDetail: "ExercireDetail",
  ExerciseDetailInstruction: "ExerciseDetailInstruction",
  ExerciseDetailRecordHistory: "ExerciseDetailRecordHistory",
  CreateNewRecords: "CreateNewRecords",
  SelectPoint: "SelectPoint",
  WorkoutPlan: "WorkoutPlan",
  MyPlan: "MyPlan",
  PlansStock: "PlansStock",
  WorkoutPlanPlansStockDetail: "WorkoutPlanPlansStockDetail",
  MyPlanIntroduction: "MyPlanIntroduction",
  MyPlanDetail: "MyPlanDetail",
  PlanDetail: "PlanDetail",
  MyPlanSelectFriend: "MyPlanSelectFriend",
  AddNewPlan: "AddNewPlan",
  AddNewPlanStep2: "AddNewPlanStep2",
  AddFood: "AddFood",
  AddFoodSimpleCalorie: "AddFoodSimpleCalorie",
  AddFoodRecent: "AddFoodRecent",
  AddFoodRecentLunch: "AddFoodRecentLunch",
  AddFoodRecentAllDay: "AddFoodRecentAllDay",
  AddFoodFrequent: "AddFoodFrequent",
  AddFoodCategory: "AddFoodCategory",
  AddFoodCategory2: "AddFoodCategory2",
  AddFoodCategory3: "AddFoodCategory3",
  MyFoodAndRecipe: "MyFoodAndRecipe",
  MyFoodAndRecipeFood: "MyFoodAndRecipeFood",
  MyFoodAndRecipeRecipes: "MyFoodAndRecipeRecipes",
  MyFoodAndRecipeMeals: "MyFoodAndRecipeMeals",
  CreateMyFoodStep1: "CreateMyFoodStep1",
  CreateMyRecipeStep1: "CreateMyRecipeStep1",
  CreateMyMealStep1: "CreateMyMealStep1",
  CreateNewFoodStep2: "CreateNewFoodStep2",
  MyFoodDetail: "MyFoodDetail",
  CreateMyRecipeStep2: "CreateMyRecipeStep2",
  MyRecipeDetail: "MyRecipeDetail",
  CreateMyMealStep2: "CreateMyMealStep2",
  MyMealDetail: "MyMealDetail",
  BlogLastet: "BlogLastet",
  BlogNutrition: "BlogNutrition",
  BlogWorkout: "BlogWorkout",
  Blog: "Blog",
  BlogNutritionDetail: "BlogNutritionDetail",
  AppsAndDevices: "AppsAndDevices",
  AppsAndDeviceConnected: "AppsAndDeviceConnected",
  AppsAndDeviceAll: "AppsAndDeviceAll",
  MyProfile: "MyProfile",
  MyProgressPhoto: "MyProgressPhoto",
  Notification: "Notification",
  PlayVideo: "PlayVideo",
  TakePhoto: "TakePhoto",
  Graph: "Graph",
  WorkoutSchedule: "WorkoutSchedule",
  DailyDetail: "DailyDetail",
  BreakfastDetail: "BreakfastDetail",
  GenerateRecipe: "GenerateRecipe",
  ListRecipes: "ListRecipes",
  ListDetailRecipes: "ListDetailRecipes",
  EditSport: "EditSport",
  EditWeight: "EditWeight",
  EditTrainingLevel: "EditTrainingLevel",
  EditSex: "EditSex",
  EditHeight: "EditHeight",
  EditName: "EditName",
};

export default Routes;
